/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Hello-OAS API
 * This is a simple hello-oas API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: feuyeux@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface Greeting
 */
export interface Greeting {
    /**
     * 
     * @type {string}
     * @memberof Greeting
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Greeting
     */
    yours: string;
    /**
     * 
     * @type {string}
     * @memberof Greeting
     */
    mine: string;
    /**
     * 
     * @type {Saying}
     * @memberof Greeting
     */
    value: Saying;
}
/**
 * 
 * @export
 * @interface Saying
 */
export interface Saying {
    /**
     * 
     * @type {number}
     * @memberof Saying
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Saying
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Saying
     */
    values: Array<string>;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum What {
    Hello = <any> 'hello',
    Bye = <any> 'bye'
}
/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id greeting identification
         * @param {What} what greeting type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayGreetings(id: number, what: What, options: any = {}): FetchArgs {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling sayGreetings.');
            }
            // verify required parameter 'what' is not null or undefined
            if (what === null || what === undefined) {
                throw new RequiredError('what','Required parameter what was null or undefined when calling sayGreetings.');
            }
            const localVarPath = `/greetings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (what !== undefined) {
                localVarQueryParameter['what'] = what;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id greeting identification
         * @param {What} what greeting type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayGreetings(id: number, what: What, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Array<Greeting>> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).sayGreetings(id, what, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {number} id greeting identification
         * @param {What} what greeting type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sayGreetings(id: number, what: What, options?: any) {
            return DefaultApiFp(configuration).sayGreetings(id, what, options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {number} id greeting identification
     * @param {What} what greeting type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public sayGreetings(id: number, what: What, options?: any) {
        return DefaultApiFp(this.configuration).sayGreetings(id, what, options)(this.fetch, this.basePath);
    }

}
