"use strict";
/**
 * Hello-OAS API
 * This is a simple hello-oas API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: feuyeux@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */
exports.__esModule = true;
var api = require("./api");
var api_1 = require("./api");
var config = {};
describe("DefaultApi", function () {
    var instance;
    beforeEach(function () {
        config.basePath = "http://localhost:8080";
        instance = new api.DefaultApi(config);
    });
    test("sayGreetings", function () {
        var id = 789;
        var what = api_1.What.Hello;
        return expect(instance.sayGreetings(id, what, {})).resolves.toBe(null);
    });
});
