// tslint:disable
/**
 * Hello-OAS API
 * This is a simple hello-oas API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: feuyeux@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
