openapi: 3.0.0
info:
  title: Hello-OAS API
  description: This is a simple hello-oas API
  contact:
    name: feuyeux
    email: feuyeux@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /greetings/{id}:
    get:
      operationId: sayGreetings
      parameters:
      - name: id
        in: path
        description: greeting identification
        required: true
        schema:
          type: integer
          format: int64
      - name: what
        in: query
        description: greeting type
        required: true
        schema:
          $ref: '#/components/schemas/What'
      responses:
        "200":
          description: greetings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Greeting'
        "400":
          description: bad input parameter
components:
  schemas:
    What:
      type: string
      enum:
      - hello
      - bye
    Greeting:
      required:
      - id
      - mine
      - value
      - yours
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        yours:
          type: string
          example: java
        mine:
          type: string
          example: go
        value:
          $ref: '#/components/schemas/Saying'
    Saying:
      required:
      - id
      - name
      - values
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: cn
        values:
          type: array
          items:
            type: string
            example: ["你好","嘿"]
