/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.27).
 * https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package org.feuyeux.oas.hello.api;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.feuyeux.oas.hello.model.Greeting;
import org.feuyeux.oas.hello.model.Saying;
import org.feuyeux.oas.hello.model.What;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class GreetingsApi {

  Logger log = LoggerFactory.getLogger(GreetingsApi.class);

  @RequestMapping(value = "/greetings/{id}", produces = {"application/json"})
  ResponseEntity<List<Greeting>> sayGreetings(@PathVariable("id") Long id,
      @RequestParam(value = "what", required = true) What what) {
    log.info("{},{}", id, what);
    List<Greeting> greetings = new ArrayList<>();
    Greeting greeting = new Greeting();
    greeting.setId(UUID.randomUUID());
    greeting.setYours("Java");
    greeting.setMine("Java");
    Saying value = new Saying();
    value.setId(1L);
    value.setName("cn");
    ArrayList<String> values = new ArrayList<>();
    values.add("你好");
    values.add("嗨");
    value.setValues(values);
    greeting.setValue(value);
    greetings.add(greeting);
    return new ResponseEntity<>(greetings, HttpStatus.OK);
  }
}

