# coding: utf-8

"""
    Hello-OAS API

    This is a simple hello-oas API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: feuyeux@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "hello-oas"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Hello-OAS API",
    author_email="feuyeux@gmail.com",
    url="",
    keywords=["Swagger", "Hello-OAS API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    This is a simple hello-oas API  # noqa: E501
    """
)
