/*
 * Hello-OAS API
 *
 * This is a simple hello-oas API
 *
 * API version: 1.0.0
 * Contact: feuyeux@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package hello

type Greeting struct {
	Id    string  `json:"id"`
	Yours string  `json:"yours"`
	Mine  string  `json:"mine"`
	Value *Saying `json:"value"`
}
