# coding: utf-8

# flake8: noqa
"""
    Hello-OAS API

    This is a simple hello-oas API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: feuyeux@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from hello_oas_client.models.greeting import Greeting
from hello_oas_client.models.saying import Saying
from hello_oas_client.models.what import What
