# coding: utf-8

"""
    Hello-OAS API

    This is a simple hello-oas API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: feuyeux@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Greeting(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'yours': 'str',
        'mine': 'str',
        'value': 'Saying'
    }

    attribute_map = {
        'id': 'id',
        'yours': 'yours',
        'mine': 'mine',
        'value': 'value'
    }

    def __init__(self, id=None, yours=None, mine=None, value=None):  # noqa: E501
        """Greeting - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._yours = None
        self._mine = None
        self._value = None
        self.discriminator = None
        self.id = id
        self.yours = yours
        self.mine = mine
        self.value = value

    @property
    def id(self):
        """Gets the id of this Greeting.  # noqa: E501


        :return: The id of this Greeting.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Greeting.


        :param id: The id of this Greeting.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def yours(self):
        """Gets the yours of this Greeting.  # noqa: E501


        :return: The yours of this Greeting.  # noqa: E501
        :rtype: str
        """
        return self._yours

    @yours.setter
    def yours(self, yours):
        """Sets the yours of this Greeting.


        :param yours: The yours of this Greeting.  # noqa: E501
        :type: str
        """
        if yours is None:
            raise ValueError("Invalid value for `yours`, must not be `None`")  # noqa: E501

        self._yours = yours

    @property
    def mine(self):
        """Gets the mine of this Greeting.  # noqa: E501


        :return: The mine of this Greeting.  # noqa: E501
        :rtype: str
        """
        return self._mine

    @mine.setter
    def mine(self, mine):
        """Sets the mine of this Greeting.


        :param mine: The mine of this Greeting.  # noqa: E501
        :type: str
        """
        if mine is None:
            raise ValueError("Invalid value for `mine`, must not be `None`")  # noqa: E501

        self._mine = mine

    @property
    def value(self):
        """Gets the value of this Greeting.  # noqa: E501


        :return: The value of this Greeting.  # noqa: E501
        :rtype: Saying
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Greeting.


        :param value: The value of this Greeting.  # noqa: E501
        :type: Saying
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Greeting, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Greeting):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
