/*
 * Hello-OAS API
 * This is a simple hello-oas API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: feuyeux@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.feuyeux.oas.hello.model;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets What
 */
@JsonAdapter(What.Adapter.class)
public enum What {
  HELLO("hello"),
  BYE("bye");

  private String value;

  What(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static What fromValue(String text) {
    for (What b : What.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<What> {
    @Override
    public void write(final JsonWriter jsonWriter, final What enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public What read(final JsonReader jsonReader) throws IOException {
      Object value = jsonReader.nextString();
      return What.fromValue(String.valueOf(value));
    }
  }
}
