/**
 * Hello-OAS API
 * This is a simple hello-oas API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: feuyeux@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"
import {What} from "./api";

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    config.basePath = "http://localhost:8080"
    instance = new api.DefaultApi(config)
  });

  test("sayGreetings", () => {
    const id: number = 789
    const what: What = What.Hello
    return expect(instance.sayGreetings(id, what, {})).resolves.toBe(null)
  })
})

