/*
 * Hello-OAS API
 * This is a simple hello-oas API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: feuyeux@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.feuyeux.oas.hello.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
