/*
 * Hello-OAS API
 *
 * This is a simple hello-oas API
 *
 * API version: 1.0.0
 * Contact: feuyeux@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package hello

type What string

// List of What
const (
	HELLO_What What = "hello"
	BYE_What   What = "bye"
)
