/*
 * Hello-OAS API
 *
 * This is a simple hello-oas API
 *
 * API version: 1.0.0
 * Contact: feuyeux@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package hello

type Saying struct {
	Id     int64    `json:"id"`
	Name   string   `json:"name"`
	Values []string `json:"values"`
}
