# coding: utf-8

"""
    Hello-OAS API

    This is a simple hello-oas API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: feuyeux@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hello_oas_client
from hello_oas_client.models.greeting import Greeting  # noqa: E501
from hello_oas_client.rest import ApiException


class TestGreeting(unittest.TestCase):
    """Greeting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGreeting(self):
        """Test Greeting"""
        # FIXME: construct object with mandatory attributes with example values
        # model = hello_oas_client.models.greeting.Greeting()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
