# coding: utf-8

"""
    Hello-OAS API

    This is a simple hello-oas API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: feuyeux@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import hello_oas_client
from hello_oas_client.api.default_api import DefaultApi  # noqa: E501
from hello_oas_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_say_greetings(self):
        """Test case for say_greetings

        """
        pass


if __name__ == '__main__':
    unittest.main()
